baseURL = 'https:/notdomquanmbs.github.io/'
title = "Dominic Keone | Cyber Portfolio"
theme = "PaperMod"
languageCode = "en-us"

[params]
  defaultTheme = "dark" # Cyber professionals always use dark mode
  description = "Cybersecurity Analyst & IT Specialist"

  [params.assets]
    disableFingerprinting = true

  [params.profileMode]
    enabled = true
    title = "Dominic Keone"
    subtitle = "Master's Student in Cybersecurity | IT Specialist"
    imageUrl = "https://github.com/your-username.png" # Uses your GitHub profile pic automatically
    imageTitle = "Dominic Keone"
    
    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/notdomquanmbs"
    [[params.socialIcons]]
      name = "linkedin"
      url = "https://linkedin.com/in/keoned"
    [[params.socialIcons]]
      name = "email"
      url = "mailto:dkeone2018@gmail.com"