baseURL = "https://notdomquanmbs.github.io/"
title = "Dominic Keone | Cyber Portfolio"
theme = "PaperMod"
languageCode = "en-us"

[params]
  defaultTheme = "dark"
  description = "Cybersecurity Analyst & IT Specialist"
  
  # This tells Hugo to relax the security check on the CSS file
  [params.assets]
    disableFingerprinting = true

  [params.profileMode]
    enabled = true
    title = "Dominic Keone"
    subtitle = "Master's Student in Cybersecurity | IT Specialist"
    imageUrl = "" # Uses your GitHub profile pic automatically
    imageTitle = "Dominic Keone"
    
    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/notdomquanmbs"
    [[params.socialIcons]]
      name = "linkedin"
      url = "https://linkedin.com/in/keoned"
    [[params.socialIcons]]
      name = "email"
      url = "mailto:dkeone2018@gmail.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 20